name: saba2v2
description: "تطبيق سبأ لتقديم خدمات مخصصة"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  go_router: 15.0.0
  file_picker: 10.1.7
  provider: 6.1.2
  dio: 5.7.0
  shared_preferences: 2.3.0
  intl: 0.19.0
  permission_handler: 11.3.1
  url_launcher: 6.1.10
  flutter_native_splash: 2.4.6
  http: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

# ✅ هنا القسم لازم يكون خارج قسم flutter
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Logo.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android: true
  ios: true
